#!/bin/sh

ARDUINO=192.168.1.119

FILES=www/*

for f in $FILES; do
    if [[ $(echo $f | egrep "~|CVS") ]]; then
	echo Skipping $f
    else
	size=`ls -l $f | awk '{print $5}'`
	echo "Uploading $f ($size bytes)"
        curl -v -0 -T $f http://$ARDUINO/upload/
    fi
done

